[project]
name = "passwii"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "quantcrypt>=1.0.1",
    "requests>=2.32.3",
]
